project:
  type: website

website:
  repo-url: https://github.com/fjuniorr/notas
  repo-actions: [edit, issue]
  navbar:
    left:
    - href: index.md
      text: Home
    right:
      - icon: github
        href: https://github.com/fjuniorr/notas
